server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_yeb?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
#      连接池名
      pool-name: DateHikariCP
      #      最小空闲数
      minimum-idle: 5
#      空闲连接存活最大时间 默认10分钟
      idle-timeout: 18000
      #      最大连接数
      maximum-pool-size: 10
      #      从连接池返回来的连接自动提交
      auto-commit: true
      #      连接存货最大时间，0表示永久 默认30分钟
      max-lifetime: 180000
      #      测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #redis
  redis:
    #    超时时间
    timeout: 10000ms
    port: 6379
    host: 127.0.0.1
    database: 2
    lettuce:
      pool:
        #        最大连接数
        max-active: 1024
        #        最大等待时间
        max-wait: 10000ms
        #        最大空闲连接
        max-idle: 200
        #        最小空闲连接
        min-idle: 5

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #  配置mybatis数据返回类型的别名
  type-aliases-package: com.ming.server.pojo
  configuration:
    #    自动驼峰命名
    map-underscore-to-camel-case: false

#mybatis sql打印
logging:
  level:
    com.ming.server.mapper: debug


#jwt
jwt:
#  jwt存储请求头
  tokenHeader: Authorization
#  密钥
  secret: yeb-secret
#  超时时间
  expiration: 604800
#  负载中拿到的开头
  tokenHead: Bearer